name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get Latest Release
        id: latest_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/Cyszx/AGMacro.github.io/releases/latest | jq -r '.assets[0].browser_download_url')
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
      
      - name: Download latest release
        run: |
          wget --no-check-certificate -O "latest_release.zip" "$LATEST_RELEASE"
      
      - name: Create download button
        run: |
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="description" content="Download Cys Macro for Anime Guardians - Enhance your gaming experience">
            <title>Cys Macros - Download Anime Guardians Macro</title>
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
            <style>
              * { margin: 0; padding: 0; box-sizing: border-box; }
              body { background: linear-gradient(135deg, #0a0a2e, #1a1a3a); font-family: "Poppins", Arial, sans-serif; padding: 20px; display: flex; justify-content: center; align-items: center; height: 100vh; color: white; }
              .container { text-align: center; background: rgba(255, 255, 255, 0.1); padding: 40px; border-radius: 10px; }
              .download-button { display: inline-block; padding: 15px 30px; background: #4CAF50; color: white; text-decoration: none; border-radius: 5px; font-size: 18px; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>Cys Macro</h1>
              <p>Enhance your gaming experience with our powerful macro tool for Anime Guardians.</p>
              <a href="latest_release.zip" class="download-button" download>⬇ Download Latest Release</a>
            </div>
          </body>
          </html>
          EOF
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
